name: Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag untuk Release (contoh: v1.0.0)'
        required: true
      release_name:
        description: 'Nama Release (opsional)'
        required: false
        default: ''
      release_body:
        description: 'Catatan rilis (opsional)'
        required: false
        default: ''
      draft:
        description: 'Buat sebagai draft? (true/false)'
        required: false
        default: 'false'
      prerelease:
        description: 'Tandai sebagai pre-release? (true/false)'
        required: false
        default: 'false'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build firmware
        run: pio run

      - name: Verify firmware files exist
        id: verify
        run: |
          shopt -s nullglob
          files=(.pio/build/*/*.bin .pio/build/*/*.elf)
          if [ ${#files[@]} -eq 0 ]; then
            echo "❌ Tidak ditemukan file firmware di .pio/build/"
            exit 1
          fi
          echo "✅ Firmware ditemukan:"
          printf ' - %s\n' "${files[@]}"

      - name: Create or update GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.release_name }}
          body: ${{ github.event.inputs.release_body }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
          allowUpdates: true
          replacesArtifacts: true
          artifacts: |
            .pio/build/*/*.bin
            .pio/build/*/*.elf
